apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-postgres-init
spec:
  template:
    spec:
      containers:
        - name: init-db
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          command:
            - sh
            - -c
            - |
              until pg_isready -h {{ .Release.Name }}-postgres -p 5432; do
                echo "Waiting for PostgreSQL to be ready..."
                sleep 5
              done
              PGPASSWORD=$POSTGRES_PASSWORD psql -h {{ .Release.Name }}-postgres -U $POSTGRES_USER -d $POSTGRES_DB -f /docker-entrypoint-initdb.d/init.sql
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-secret
                  key: postgres-password
            - name: POSTGRES_DB
              value: {{ .Values.db.postgresDatabase }}
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      restartPolicy: OnFailure
      volumes:
        - name: init-script
          configMap:
            name: {{ .Release.Name }}-postgres-init-script
