apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
type: Opaque
data:
  postgres-password: {{ .Values.db.postgresPassword | b64enc | quote }}
  postgres-user: {{ .Values.db.postgresUser | b64enc | quote }}
