name: Test Gradle project

on: [push, pull_request]

jobs:

  lint-gradle-project:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project source
      uses: actions/checkout@v4

    - name: Set Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Run lint
      run: ./gradlew lint

  build-gradle-project:
    runs-on: ubuntu-latest

    needs: lint-gradle-project

    steps:
    - name: Checkout project source
      uses: actions/checkout@v4

    - name: Set Java
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Run build without tests
      run: ./gradlew assemble

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: popopolette
          password: ${{ secrets.POPOPOLETTE }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: popopolette/app:latest

      - name: Run Docker Compose
        run: docker-compose -f compose.yml up -d


    needs: lint-gradle-project